"""
This type stub file was generated by pyright.
"""

from kivy.input.provider import MotionEventProvider
from kivy.input.motionevent import MotionEvent

"""
This type stub file was generated by pyright.
"""
__all__ = ('MouseMotionEventProvider', )
Ellipse = ...
class MouseMotionEvent(MotionEvent):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def depack(self, args):
        ...
    
    def update_graphics(self, win, create=...):
        ...
    
    def clear_graphics(self, win):
        ...
    


class MouseMotionEventProvider(MotionEventProvider):
    __handlers__ = ...
    def __init__(self, device, args) -> None:
        ...
    
    disable_hover = ...
    def start(self):
        '''Start the mouse provider'''
        ...
    
    def stop(self):
        '''Stop the mouse provider'''
        ...
    
    def test_activity(self):
        ...
    
    def find_touch(self, win, x, y):
        ...
    
    def create_event_id(self):
        ...
    
    def create_touch(self, win, nx, ny, is_double_tap, do_graphics, button):
        ...
    
    def remove_touch(self, win, touch):
        ...
    
    def create_hover(self, win, etype):
        ...
    
    def on_mouse_motion(self, win, x, y, modifiers):
        ...
    
    def on_mouse_press(self, win, x, y, button, modifiers):
        ...
    
    def on_mouse_release(self, win, x, y, button, modifiers):
        ...
    
    def update_touch_graphics(self, win, *args):
        ...
    
    def begin_or_update_hover_event(self, win, *args):
        ...
    
    def begin_hover_event(self, win, *args):
        ...
    
    def update_hover_event(self, win, *args):
        ...
    
    def end_hover_event(self, win, *args):
        ...
    
    def update(self, dispatch_fn):
        '''Update the mouse provider (pop event from the queue)'''
        ...
    


