"""
This type stub file was generated by pyright.
"""

import os
from kivy.input.provider import MotionEventProvider

"""
This type stub file was generated by pyright.
"""
__all__ = ('ProbeSysfsHardwareProbe', )
if 'KIVY_DOC' in os.environ:
    ProbeSysfsHardwareProbe = ...
else:
    EventLoop = ...
    ABS_MT_POSITION_X = ...
    _cache_input = ...
    _cache_xinput = ...
    class Input:
        def __init__(self, path) -> None:
            ...
        
        @property
        def device(self):
            ...
        
        @property
        def name(self):
            ...
        
        def get_capabilities(self):
            ...
        
        def has_capability(self, capability):
            ...
        
        @property
        def is_mouse(self):
            ...
        
    
    
    def getout(*args):
        ...
    
    def query_xinput():
        ...
    
    def get_inputs(path):
        ...
    
    def read_line(path):
        ...
    
    class ProbeSysfsHardwareProbe(MotionEventProvider):
        def __new__(self, device, args):
            ...
        
        def __init__(self, device, args) -> None:
            ...
        
        def should_use_mouse(self):
            ...
        
        def probe(self):
            ...
        
    
    
