"""
This type stub file was generated by pyright.
"""

import os
from kivy.input.motionevent import MotionEvent
from kivy.input.provider import MotionEventProvider

"""
This type stub file was generated by pyright.
"""
__all__ = ('WM_PenProvider', 'WM_Pen')
class WM_Pen(MotionEvent):
    '''MotionEvent representing the WM_Pen event. Supports the pos profile.'''
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def depack(self, args):
        ...
    
    def __str__(self) -> str:
        ...
    


if 'KIVY_DOC' in os.environ:
    WM_PenProvider = ...
else:
    win_rect = ...
    class WM_PenProvider(MotionEventProvider):
        def start(self):
            ...
        
        def update(self, dispatch_fn):
            ...
        
        def stop(self):
            ...
        
    
    
