"""
This type stub file was generated by pyright.
"""

from .circularoutput import CircularOutput
from .ffmpegoutput import FfmpegOutput
from .fileoutput import FileOutput
from .output import Output

