"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Any, Dict, Mapping, Sequence

"""Piper configuration"""
class PhonemeType(str, Enum):
    ESPEAK = ...
    TEXT = ...


@dataclass
class PiperConfig:
    """Piper configuration"""
    num_symbols: int
    num_speakers: int
    sample_rate: int
    espeak_voice: str
    length_scale: float
    noise_scale: float
    noise_w: float
    phoneme_id_map: Mapping[str, Sequence[int]]
    phoneme_type: PhonemeType
    @staticmethod
    def from_dict(config: Dict[str, Any]) -> PiperConfig:
        ...
    


