"""
This type stub file was generated by pyright.
"""

from kivy.graphics.instructions import Callback, Canvas, CanvasBase, ContextInstruction, Instruction, InstructionGroup, RenderContext, VertexInstruction
from kivy.graphics.context_instructions import ApplyContextMatrix, BindTexture, ChangeState, Color, LoadIdentity, MatrixInstruction, PopMatrix, PopState, PushMatrix, PushState, Rotate, Scale, Translate, UpdateNormalMatrix, gl_init_resources
from kivy.graphics.vertex_instructions import Bezier, BorderImage, Ellipse, GraphicException, Line, Mesh, Point, Quad, Rectangle, RoundedRectangle, SmoothEllipse, SmoothLine, SmoothQuad, SmoothRectangle, SmoothRoundedRectangle, SmoothTriangle, Triangle
from kivy.graphics.stencil_instructions import StencilPop, StencilPush, StencilUnUse, StencilUse
from kivy.graphics.gl_instructions import ClearBuffers, ClearColor
from kivy.graphics.fbo import Fbo
from kivy.graphics.boxshadow import BoxShadow
from kivy.graphics.scissor_instructions import ScissorPop, ScissorPush

"""
This type stub file was generated by pyright.
"""
__all__ = (Bezier.__name__, BindTexture.__name__, BorderImage.__name__, Callback.__name__, Canvas.__name__, CanvasBase.__name__, Color.__name__, ContextInstruction.__name__, Ellipse.__name__, Fbo.__name__, GraphicException.__name__, Instruction.__name__, InstructionGroup.__name__, Line.__name__, SmoothLine.__name__, MatrixInstruction.__name__, Mesh.__name__, Point.__name__, PopMatrix.__name__, PushMatrix.__name__, Quad.__name__, Rectangle.__name__, RenderContext.__name__, Rotate.__name__, Scale.__name__, StencilPop.__name__, StencilPush.__name__, StencilUse.__name__, StencilUnUse.__name__, Translate.__name__, Triangle.__name__, VertexInstruction.__name__, ClearColor.__name__, ClearBuffers.__name__, gl_init_resources.__name__, PushState.__name__, ChangeState.__name__, PopState.__name__, ApplyContextMatrix.__name__, UpdateNormalMatrix.__name__, LoadIdentity.__name__, BoxShadow.__name__, SmoothEllipse.__name__, SmoothRoundedRectangle.__name__, SmoothRectangle.__name__, SmoothQuad.__name__, SmoothTriangle.__name__)
