MIXER_CHANNEL_ALL = ...
PCM_PLAYBACK = ...
PCM_CAPTURE = ...

def cards() -> list[str]: ...

class ALSAAudioError(BaseException): ...

class Mixer:
    def __init__(self, control: str, cardindex: int = ...) -> None: ...
    def setvolume(self, volume: float, channel: int = 0, pcm: int = 0) -> None: ...
    def setrec(self, volume: float) -> None: ...
    def setmute(self, volume: int) -> None: ...
