MIXER_CHANNEL_ALL = ...
PCM_PLAYBACK = 0
PCM_CAPTURE = 1

PCM_NORMAL = 0

PCM_FORMAT_S16_LE = 2
PCM_FORMAT_FLOAT64_LE = 64

def cards() -> list[str]: ...

class ALSAAudioError(BaseException): ...

class Mixer:
    def __init__(self, control: str, cardindex: int = ...) -> None: ...
    def setvolume(self, volume: float, channel: int = 0, pcm: int = 0) -> None: ...
    def setrec(self, volume: float) -> None: ...
    def setmute(self, volume: int) -> None: ...

class PCM:
    def __init__(
        self,
        cardindex: int,
        mode: int = PCM_PLAYBACK,
        /,
        channels: int = 2,
        rate: int = 44100,
        format: int = PCM_FORMAT_FLOAT64_LE,
        periodsize: int = 125_000,
    ) -> None: ...
    def write(self, data: bytes) -> None: ...
    def read(self, size: int = 0) -> tuple[int, bytes]: ...
    def prepare(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def close(self) -> None: ...
    def avail(self) -> int: ...
    def delay(self) -> int: ...
    def setformat(self, format: int) -> None: ...
    def setrate(self, rate: int) -> None: ...
    def setchannels(self, channels: int) -> None: ...
    def setperiodsize(self, size: int) -> None: ...
    def setperiodtime(self, time: int) -> None: ...
    def setfragments(self, fragments: int) -> None: ...
    def setstartthreshold(self, threshold: int) -> None: ...
    def setavailmin(self, availmin: int) -> None: ...
    def setswparams(self, swparams: list[int]) -> None: ...
    def sethwparams(self, hwparams: list[int]) -> None: ...
    def setparams(self, params: list[int]) -> None: ...
    def getparams(self) -> list[int]: ...
    def getswparams(self) -> list[int]: ...
    def gethwparams(self) -> list[int]: ...
    def getrate(self) -> int: ...
    def getchannels(self) -> int: ...
    def getformat(self) -> int: ...
    def getperiodsize(self) -> int: ...
    def getperiodtime(self) -> int: ...
    def getfragments(self) -> int: ...
    def getstartthreshold(self) -> int: ...
    def getavailmin(self) -> int: ...
    def getavail(self) -> int: ...
    def getdelay(self) -> int: ...
    def getstatus(self) -> int: ...
    def getfileposition(self) -> int: ...
    def getcaps(self) -> int: ...
    def getname(self) -> str: ...
    def getcardname(self) -> str: ...
    def getid(self) -> str: ...
    def getcardid(self) -> str: ...
    def getdev(self) -> str: ...
    def getcard(self) -> int: ...
