"""
This type stub file was generated by pyright.
"""

from __future__ import annotations
from .parse import parse_get_managed_objects, parse_interfaces_added, parse_interfaces_removed, parse_properties_changed

__all__ = ("parse_get_managed_objects", "parse_interfaces_added", "parse_interfaces_removed", "parse_properties_changed")
