"""
This type stub file was generated by pyright.
"""

from typing import Optional, TYPE_CHECKING, Union
from ..dbus_proxy_async_interface_base import DbusInterfaceBaseAsync
from ..dbus_proxy_sync_interface_base import DbusInterfaceBase
from ..sd_bus_internals import SdBus

if TYPE_CHECKING:
    ...
def inspect_dbus_path(obj: Union[DbusInterfaceBase, DbusInterfaceBaseAsync], bus: Optional[SdBus] = ...) -> str:
    ...

