"""
This type stub file was generated by pyright.
"""

from kivy.utils import platform

"""
This type stub file was generated by pyright.
"""
__all__ = ('resource_find', 'resource_add_path', 'resource_remove_path')
resource_paths = ...
if platform == 'ios':
    ...
def resource_find(filename, use_cache=...):
    '''Search for a resource in the list of paths.
    Use resource_add_path to add a custom path to the search.
    By default, results are cached for 60 seconds.
    This can be disabled using use_cache=False.

    .. versionchanged:: 2.1.0
        `use_cache` parameter added and made True by default.
    '''
    ...

def resource_add_path(path):
    '''Add a custom path to search in.
    '''
    ...

def resource_remove_path(path):
    '''Remove a search path.

    .. versionadded:: 1.0.8
    '''
    ...

