"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
__all__ = ('InputPostprocTripleTap', )
class InputPostprocTripleTap:
    '''
    InputPostProcTripleTap is a post-processor to check if
    a touch is a triple tap or not.
    Triple tap can be configured in the Kivy config file::

        [postproc]
        triple_tap_time = 250
        triple_tap_distance = 20

    The distance parameter is in the range 0-1000 and time is in milliseconds.
    '''
    def __init__(self) -> None:
        ...
    
    def find_triple_tap(self, ref):
        '''Find a triple tap touch within *self.touches*.
        The touch must be not be a previous triple tap and the distance
        must be within the bounds specified. Additionally, the touch profile
        must be the same kind of touch.
        '''
        ...
    
    def process(self, events):
        ...
    


