"""
This type stub file was generated by pyright.
"""

class Metadata:
    def __init__(self, metadata=...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def make_dict(self): # -> dict[str, Any]:
        ...
    


