"""
This type stub file was generated by pyright.
"""

from libcamera import Transform

class SensorFormat:
    def __init__(self, fmt_string) -> None:
        ...
    
    @property
    def format(self): # -> str:
        ...
    
    @property
    def unpacked(self): # -> str:
        ...
    
    @property
    def mono(self): # -> bool:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def transform(self, transform: Transform): # -> None:
        ...
    


