"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Optional
from .base import NetworkManagerSettingsMixin

@dataclass
class BondPortSettings(NetworkManagerSettingsMixin):
    """Bond Port Settings"""
    queue_id: Optional[int] = ...


