"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Dict, Optional
from .base import NetworkManagerSettingsMixin

@dataclass
class BondSettings(NetworkManagerSettingsMixin):
    """Bonding Settings"""
    interface_name: Optional[str] = ...
    options: Optional[Dict[str, str]] = ...


