"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import List, Optional
from .base import NetworkManagerSettingsMixin
from .datatypes import Vlans

@dataclass
class BridgePortSettings(NetworkManagerSettingsMixin):
    """Bridge Port Settings"""
    hairpin_mode: Optional[bool] = ...
    path_cost: Optional[int] = ...
    priority: Optional[int] = ...
    vlans: Optional[List[Vlans]] = ...


