"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from .base import NetworkManagerSettingsMixin

@dataclass
class EthtoolSettings(NetworkManagerSettingsMixin):
    """Ethtool Ethernet Settings"""
    ...


