"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Optional
from .base import NetworkManagerSettingsMixin

@dataclass
class HostnameSettings(NetworkManagerSettingsMixin):
    """Hostname settings"""
    from_dhcp: Optional[int] = ...
    from_dns_lookup: Optional[int] = ...
    only_from_default: Optional[int] = ...
    priority: Optional[int] = ...


