"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Optional
from .base import NetworkManagerSettingsMixin

@dataclass
class InfinibandSettings(NetworkManagerSettingsMixin):
    """Infiniband Settings"""
    mac_address: Optional[bytes] = ...
    mtu: Optional[int] = ...
    p_key: Optional[int] = ...
    parent: Optional[str] = ...
    transport_mode: Optional[str] = ...


