"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Optional
from .base import NetworkManagerSettingsMixin

@dataclass
class MacvlanSettings(NetworkManagerSettingsMixin):
    """MAC VLAN Settings"""
    mode: Optional[int] = ...
    parent: Optional[str] = ...
    promiscuous: Optional[bool] = ...
    tap: Optional[bool] = ...


