"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import List, Optional
from .base import NetworkManagerSettingsMixin

@dataclass
class MatchSettings(NetworkManagerSettingsMixin):
    """Match settings"""
    driver: Optional[List[str]] = ...
    interface_name: Optional[List[str]] = ...
    kernel_command_line: Optional[List[str]] = ...
    path: Optional[List[str]] = ...


