"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Optional
from .base import NetworkManagerSettingsMixin

@dataclass
class OlpcMeshSettings(NetworkManagerSettingsMixin):
    """OLPC Wireless Mesh Settings"""
    channel: Optional[int] = ...
    dhcp_anycast_address: Optional[bytes] = ...
    ssid: Optional[bytes] = ...


