"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Optional
from .base import NetworkManagerSettingsMixin

@dataclass
class OvsBridgeSettings(NetworkManagerSettingsMixin):
    """OvsBridge Link Settings"""
    datapath_type: Optional[str] = ...
    fail_mode: Optional[str] = ...
    mcast_snooping_enable: Optional[bool] = ...
    rstp_enable: Optional[bool] = ...
    stp_enable: Optional[bool] = ...


