"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Optional
from .base import NetworkManagerSettingsMixin

@dataclass
class ProxySettings(NetworkManagerSettingsMixin):
    """WWW Proxy Settings"""
    browser_only: Optional[bool] = ...
    method: Optional[int] = ...
    pac_script: Optional[str] = ...
    pac_url: Optional[str] = ...


