"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import List, Optional
from .base import NetworkManagerSettingsMixin
from .datatypes import Vfs

@dataclass
class SriovSettings(NetworkManagerSettingsMixin):
    """SR-IOV settings"""
    autoprobe_drivers: Optional[int] = ...
    total_vfs: Optional[int] = ...
    vfs: Optional[List[Vfs]] = ...


