"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Dict, Optional
from .base import NetworkManagerSettingsMixin

@dataclass
class UserSettings(NetworkManagerSettingsMixin):
    """General User Profile Settings"""
    data: Optional[Dict[str, str]] = ...


