"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Optional
from .base import NetworkManagerSettingsMixin

@dataclass
class WifiP2PSettings(NetworkManagerSettingsMixin):
    """Wi-Fi P2P Settings"""
    peer: Optional[str] = ...
    wfd_ies: Optional[bytes] = ...
    wps_method: Optional[int] = ...


