"""
This type stub file was generated by pyright.
"""

from picamera2.previews.null_preview import *

class DrmManager:
    def __init__(self) -> None:
        ...
    
    def add(self, drm_preview): # -> None:
        ...
    
    def remove(self, drm_preview): # -> None:
        ...
    


class DrmPreview(NullPreview):
    FMT_MAP = ...
    _manager = ...
    def __init__(self, x=..., y=..., width=..., height=..., transform=...) -> None:
        ...
    
    def render_request(self, completed_request): # -> None:
        """Draw the camera image using DRM."""
        ...
    
    def handle_request(self, picam2): # -> None:
        ...
    
    def init_drm(self, x, y, width, height, transform): # -> None:
        ...
    
    def set_overlay(self, overlay): # -> None:
        ...
    
    def render_drm(self, picam2, completed_request): # -> None:
        ...
    
    def stop(self): # -> None:
        ...
    


