"""
This type stub file was generated by pyright.
"""

from kivy import Logger
from kivy.core import core_select_lib
from kivy.utils import platform
from kivy.setupconfig import USE_SDL2

'''
Clipboard
=========

Core class for accessing the Clipboard. If we are not able to access the
system clipboard, a fake one will be used.

Usage example:

.. code-block:: kv

    #:import Clipboard kivy.core.clipboard.Clipboard

    Button:
        on_release:
            self.text = Clipboard.paste()
            Clipboard.copy('Data')
'''
__all__ = ('ClipboardBase', 'Clipboard')
class ClipboardBase:
    def get(self, mimetype): # -> None:
        '''Get the current data in clipboard, using the mimetype if possible.
        You not use this method directly. Use :meth:`paste` instead.
        '''
        ...
    
    def put(self, data, mimetype): # -> None:
        '''Put data on the clipboard, and attach a mimetype.
        You should not use this method directly. Use :meth:`copy` instead.
        '''
        ...
    
    def get_types(self): # -> list[Any]:
        '''Return a list of supported mimetypes
        '''
        ...
    
    def copy(self, data=...): # -> None:
        ''' Copy the value provided in argument `data` into current clipboard.
        If data is not of type string it will be converted to string.

        .. versionadded:: 1.9.0

        '''
        ...
    
    def paste(self): # -> Literal['']:
        ''' Get text from the system clipboard and return it a usable string.

        .. versionadded:: 1.9.0

        '''
        ...
    


_clipboards = ...
if platform == 'android':
    ...
else:
    ...
if USE_SDL2:
    ...
else:
    ...
Clipboard = ...
CutBuffer = ...
if platform == 'linux':
    _cutbuffers = ...
