"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
__all__ = ('MotionEventProvider', )
class MotionEventProvider:
    '''Base class for a provider.
    '''
    def __init__(self, device, args) -> None:
        ...
    
    def start(self):
        '''Start the provider. This method is automatically called when the
        application is started and if the configuration uses the current
        provider.
        '''
        ...
    
    def stop(self):
        '''Stop the provider.
        '''
        ...
    
    def update(self, dispatch_fn):
        '''Update the provider and dispatch all the new touch events though the
        `dispatch_fn` argument.
        '''
        ...
    


