"""
This type stub file was generated by pyright.
"""

'''
Motion Event Shape
==================

Represent the shape of the :class:`~kivy.input.motionevent.MotionEvent`
'''
__all__ = ('Shape', 'ShapeRect')
class Shape:
    '''Abstract class for all implementations of a shape'''
    ...


class ShapeRect(Shape):
    '''Class for the representation of a rectangle.'''
    __slots__ = ...
    def __init__(self) -> None:
        ...
    


