"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Tuple

NetworkManagerSetting = Tuple[str, Any]
NetworkManagerSettingsDomain = Dict[str, NetworkManagerSetting]
NetworkManagerConnectionProperties = Dict[str, NetworkManagerSettingsDomain]
SettingsDict = Dict[str, Dict[str, Any]]
