"""
This type stub file was generated by pyright.
"""

from picamera2.allocators.allocator import Allocator, Sync

_log = ...
class DmaAllocator(Allocator):
    """DmaHeap Allocator"""
    def __init__(self) -> None:
        ...
    
    def allocate(self, libcamera_config, _): # -> None:
        ...
    
    def buffers(self, stream):
        ...
    
    def acquire(self, buffers): # -> None:
        ...
    
    def release(self, buffers): # -> None:
        ...
    
    def cleanup(self): # -> None:
        ...
    
    def close(self): # -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    class DmaSync(Sync):
        """Dma Buffer Sync"""
        def __init__(self, allocator, fb, write) -> None:
            ...
        
        def __enter__(self):
            ...
        
        def __exit__(self, exc_type=..., exc_value=..., exc_traceback=...): # -> None:
            ...
        
    
    


