"""
This type stub file was generated by pyright.
"""

from picamera2.allocators.allocator import Allocator

_log = ...
class LibcameraAllocator(Allocator):
    """Uses the libcamera FrameBufferAllocator"""
    def __init__(self, camera) -> None:
        ...
    
    def allocate(self, libcamera_config, _): # -> None:
        ...
    
    def buffers(self, stream):
        ...
    


