"""
This type stub file was generated by pyright.
"""

from picamera2.allocators import DmaAllocator

_log = ...
class PersistentAllocator(DmaAllocator):
    """Persistent DmaHeap Allocator"""
    def __init__(self) -> None:
        ...
    
    def allocate(self, libcamera_config, use_case): # -> None:
        ...
    
    def cleanup(self): # -> None:
        ...
    
    def deallocate(self, buffer_key=...): # -> None:
        """Deallocate a set of buffers if no longer in use"""
        ...
    
    def close(self): # -> None:
        ...
    


