"""
This type stub file was generated by pyright.
"""

import apt_pkg
from typing import Optional
from apt.progress.base import CdromProgress

"""
This type stub file was generated by pyright.
"""
class Cdrom(apt_pkg.Cdrom):
    """Support for apt-cdrom like features.

    This class has several optional parameters for initialisation, which may
    be used to influence the behaviour of the object:

    The optional parameter `progress` is a CdromProgress() subclass, which will
    ask for the correct cdrom, etc. If not specified or None, a CdromProgress()
    object will be used.

    The optional parameter `mountpoint` may be used to specify an alternative
    mountpoint.

    If the optional parameter `nomount` is True, the cdroms will not be
    mounted. This is the default behaviour.
    """
    def __init__(self, progress: Optional[CdromProgress] = ..., mountpoint: Optional[str] = ..., nomount: bool = ...) -> None:
        ...
    
    def add(self, progress: Optional[CdromProgress] = ...) -> bool:
        """Add cdrom to the sources.list."""
        ...
    
    def ident(self, progress: Optional[CdromProgress] = ...) -> str:
        """Identify the cdrom."""
        ...
    
    @property
    def in_sources_list(self) -> bool:
        """Check if the cdrom is already in the current sources.list."""
        ...
    


