"""
This type stub file was generated by pyright.
"""

import datetime
import apt
from typing import Optional, Tuple

"""
This type stub file was generated by pyright.
"""
def get_maintenance_end_date(release_date: datetime.datetime, m_months: int) -> Tuple[int, int]:
    """
    get the (year, month) tuple when the maintenance for the distribution
    ends. Needs the data of the release and the number of months that
    its is supported as input
    """
    ...

def get_release_date_from_release_file(path: str) -> Optional[int]:
    """
    return the release date as time_t for the given release file
    """
    ...

def get_release_filename_for_pkg(cache: apt.Cache, pkgname: str, label: str, release: str) -> Optional[str]:
    "get the release file that provides this pkg"
    ...

