"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    ...
def run_gen_from_connection(connection_name: str, object_paths: List[str], system: bool, imports_header: bool, do_async: bool) -> None:
    ...

def run_gen_from_file(filenames: List[str], imports_header: bool, do_async: bool) -> None:
    ...

def generator_main(args: Optional[List[str]] = ...) -> None:
    ...

if __name__ == "__main__":
    ...
