"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Optional, TYPE_CHECKING, Type, TypeVar
from .dbus_common_elements import DbusBindedSync, DbusMethodCommon, DbusSomethingSync
from .dbus_proxy_sync_interface_base import DbusInterfaceBase

if TYPE_CHECKING:
    ...
T = TypeVar('T')
class DbusMethodSync(DbusMethodCommon, DbusSomethingSync):
    def __get__(self, obj: DbusInterfaceBase, obj_class: Optional[Type[DbusInterfaceBase]] = ...) -> Callable[..., Any]:
        ...
    


class DbusMethodSyncBinded(DbusBindedSync):
    def __init__(self, dbus_method: DbusMethodSync, interface: DbusInterfaceBase) -> None:
        ...
    
    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        ...
    


def dbus_method(input_signature: str = ..., result_signature: str = ..., flags: int = ..., method_name: Optional[str] = ...) -> Callable[[T], T]:
    ...

