"""
This type stub file was generated by pyright.
"""

from asyncio import Future
from contextvars import ContextVar
from typing import Generator, TYPE_CHECKING
from .sd_bus_internals import SdBus

if TYPE_CHECKING:
    ...
DEFAULT_BUS: ContextVar[SdBus] = ...
PROPERTY_FLAGS_MASK = ...
def count_bits(i: int) -> int:
    ...

def get_default_bus() -> SdBus:
    ...

def set_default_bus(new_default: SdBus) -> None:
    ...

async def request_default_bus_name_async(new_name: str, allow_replacement: bool = ..., replace_existing: bool = ..., queue: bool = ...) -> None:
    ...

class _DeprecationAwaitable:
    def __await__(self) -> Generator[Future[None], None, None]:
        ...
    


def request_default_bus_name(new_name: str, allow_replacement: bool = ..., replace_existing: bool = ..., queue: bool = ...) -> _DeprecationAwaitable:
    ...

