"""
This type stub file was generated by pyright.
"""

from picamera2.encoders.v4l2_encoder import V4L2Encoder

"""MJPEG encoder functionality utilising V4L2"""
class MJPEGEncoder(V4L2Encoder):
    """MJPEG encoder utilsing V4L2 functionality"""
    def __init__(self, bitrate=...) -> None:
        """Creates MJPEG encoder

        :param bitrate: Bitrate, default None
        :type bitrate: int
        """
        ...
    


